// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108095951_UpdateUtilizatorNrTelefon")]
    partial class UpdateUtilizatorNrTelefon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Aplicare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Created_at")
                        .HasColumnType("date");

                    b.Property<int>("Id_Meserias")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Oferta")
                        .HasColumnType("integer");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_Meserias");

                    b.HasIndex("Id_Oferta");

                    b.ToTable("Aplicari");
                });

            modelBuilder.Entity("Backend.Models.Favorit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_meserias")
                        .HasColumnType("integer");

                    b.Property<int>("Id_user")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_meserias");

                    b.HasIndex("Id_user");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("Backend.Models.Judet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Judete");
                });

            modelBuilder.Entity("Backend.Models.Meserias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_user")
                        .HasColumnType("integer");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disponibilitate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Experienta")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Judet")
                        .HasColumnType("integer");

                    b.Property<decimal>("Pret_start")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id", "Id_user");

                    b.HasIndex("Id_Judet");

                    b.HasIndex("Id_user");

                    b.ToTable("Meseriasi");
                });

            modelBuilder.Entity("Backend.Models.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Buget")
                        .HasColumnType("real");

                    b.Property<DateOnly>("Created_at")
                        .HasColumnType("date");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_judet")
                        .HasColumnType("integer");

                    b.Property<int>("Id_specializare")
                        .HasColumnType("integer");

                    b.Property<int>("Id_user")
                        .HasColumnType("integer");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_judet");

                    b.HasIndex("Id_specializare");

                    b.HasIndex("Id_user");

                    b.ToTable("Oferte");
                });

            modelBuilder.Entity("Backend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Created_at")
                        .HasColumnType("date");

                    b.Property<int>("Id_Meserias")
                        .HasColumnType("integer");

                    b.Property<int>("Id_User")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Recenzie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_Meserias");

                    b.HasIndex("Id_User");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Backend.Models.Specializare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specializari");
                });

            modelBuilder.Entity("Backend.Models.SpecializareMeserias", b =>
                {
                    b.Property<int>("Id_meserias")
                        .HasColumnType("integer");

                    b.Property<int>("Id_specializare")
                        .HasColumnType("integer");

                    b.HasKey("Id_meserias", "Id_specializare");

                    b.HasIndex("Id_specializare");

                    b.ToTable("SpecializariMeseriasi");
                });

            modelBuilder.Entity("Backend.Models.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Created_at")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Data_Nasterii")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsteMeserias")
                        .HasColumnType("boolean");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parola_Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilizatori");
                });

            modelBuilder.Entity("Backend.Models.Aplicare", b =>
                {
                    b.HasOne("Backend.Models.Meserias", "Meserias")
                        .WithMany()
                        .HasForeignKey("Id_Meserias")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Oferta", "Oferta")
                        .WithMany()
                        .HasForeignKey("Id_Oferta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meserias");

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("Backend.Models.Favorit", b =>
                {
                    b.HasOne("Backend.Models.Meserias", "Meserias")
                        .WithMany()
                        .HasForeignKey("Id_meserias")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meserias");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Backend.Models.Meserias", b =>
                {
                    b.HasOne("Backend.Models.Judet", "Judet")
                        .WithMany()
                        .HasForeignKey("Id_Judet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Judet");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Backend.Models.Oferta", b =>
                {
                    b.HasOne("Backend.Models.Judet", "Judet")
                        .WithMany()
                        .HasForeignKey("Id_judet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Specializare", "Specializare")
                        .WithMany()
                        .HasForeignKey("Id_specializare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Judet");

                    b.Navigation("Specializare");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Backend.Models.Review", b =>
                {
                    b.HasOne("Backend.Models.Meserias", "Meserias")
                        .WithMany()
                        .HasForeignKey("Id_Meserias")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meserias");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Backend.Models.SpecializareMeserias", b =>
                {
                    b.HasOne("Backend.Models.Meserias", "Meserias")
                        .WithMany()
                        .HasForeignKey("Id_meserias")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Specializare", "Specializare")
                        .WithMany()
                        .HasForeignKey("Id_specializare")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meserias");

                    b.Navigation("Specializare");
                });
#pragma warning restore 612, 618
        }
    }
}
